### ISSUE TITLE
Can I import this repository into Translation for The Outsider?

### ISSUE THREAD

**Issue by TRSasasusu** [nice2cu1/TheOutsider_CN#1]
I would like to use your great Chinese translation of The Outsider.

I am making [Translation for The Outsider](https://outerwildsmods.com/mods/translationfortheoutsider/), which is an addon for translating [The Outsider](https://outerwildsmods.com/mods/theoutsider/). Now, it has Brazilian Portuguese and Japanese translation, and I would like to add your Chinese translation.

Is that ok?

**Comment by nice2cu1** [comment]
@TRSasasusu If you want, of course you can. 
But you need to know that the current Chinese translation is not perfect, and most of the translations come from the community (and a few of my personal understanding of the story). 
Therefore, I can't guarantee the accuracy.

**Comment by TRSasasusu** [comment]
@nice2cu1 Thank you for your reply!
I think that the translation is great, so I will try importing it.
After completing, I will tell you here.

**Comment by nice2cu1** [comment]
@TRSasasusu For the Chinese translation, I encountered a lack of words, such as "宇宙之眼" displayed as "宇宙眼".
I don't know much about Unity. Assumption: It was the font that was wrong, so I did [OuterWildFixFont](https://github.com/nice2cu1/OuterWildFixFont) to fix it, and I also made some changes to [Outer-Wilds-The-Outsider](https://github.com/nice2cu1/Outer-Wilds-The-Outsider/commit/9a4bdccede69a87c3ca5a60870eb15c2450ed918).
I hope these contents can help you.
Good luck with your work！Cheers to adventure!

**Comment by TRSasasusu** [comment]
Thanks to your [OuterWildFixFont](https://github.com/nice2cu1/OuterWildFixFont), the texts displayed correctly, I think. This is a really great work!

![スクリーンショット (2106)](https://user-images.githubusercontent.com/17728957/233780104-bbf876d5-cb28-4c43-85bd-55001a099d1b.png)
![スクリーンショット (2111)](https://user-images.githubusercontent.com/17728957/233780112-fc6ed471-5ddb-4d4a-81d3-9e7d4a9a5603.png)
![スクリーンショット (2109)](https://user-images.githubusercontent.com/17728957/233780118-240bd25d-0686-4fe5-baf4-4702b7195a96.png)

I will release it at soon with noting that installing OuterWildFixFont is recommended for Chinese translation.

**Comment by TRSasasusu** [comment]
It is released as [v0.4.0](https://github.com/TRSasasusu/TranslationForTheOutsider/releases/tag/v0.4.0), and [available in the mod manager](https://outerwildsmods.com/mods/translationfortheoutsider/). Thank you for your helping!
